ENABLE_REQUEST_RETRY = True
FAILURE_REQUEST_RETRY_TIMEOUT = 5
MAX_RETRY_NUM = 1
REQUEST_WAITING_TIMEOUT = 15
GLOBAL_DETECTION_SCAN_TIMEOUT = 10

RECOVERY_TASK_TIMEOUT = 20

ENABLE_SCALING = True
TRAFFIC_LOAD_DETECT_TIMESLOT = 5
MAX_OVER_LOAD_NUM_THRESHOLD = 3
MAX_UNDER_LOAD_NUM_THRESHOLD = 5

DEBUG_MODE = True
DEBUG_MODE_LOG_TIMESLOT = 1
