ENABLE_REQUEST_RETRY = True
FAILURE_REQUEST_RETRY_TIMEOUT = 5
MAX_RETRY_NUM = 2
REQUEST_WAITING_TIMEOUT = 30

ENABLE_SCALING = True
TRAFFIC_LOAD_DETECT_TIMESLOT = 5
MAX_OVER_LOAD_NUM_THRESHOLD = 3
MAX_UNDER_LOAD_NUM_THRESHOLD = 5
