#!/usr/bin/python
# -*- coding: UTF-8 -*-

SWITCH_CONF_FILEPATH = "./conf/switch.yaml"
ZONE_NAME = ""

MAIN_TABLE = 0
IPV4_CLASSIFIER_TABLE = 1
WEST_EAST_TABLE = 2
NORTH_SOUTH_TABLE = 3
VLAN_TABLE = 4
NOTVIA_TABLE = 5
UFRR_TABLE = 6
L2_TABLE = 7

DEFAULT_DCN_GATEWAY_OUTBOUND_PORT_NUMBER = 1
DCNGATEWAY_INBOUND_PORT = 1
SWITCH_CLASSIFIER_PORT = 3