#!/usr/bin/python
# -*- coding: UTF-8 -*-

SWITCH_CONF_FILEPATH = "./conf/switch.yaml"
ZONE_NAME = ""

MAIN_TABLE = 0

DEFAULT_DCN_GATEWAY_OUTBOUND_PORT_NUMBER = 1
DCNGATEWAY_INBOUND_PORT = 1

SOFTWARE_SFF = "SOFTWARE_SFF"
HARDWARE_SFF = "HARDWARE_SFF"

MININET_ENV = "MININET_ENV"
PICA8_ENV = "PICA8_ENV "
CURRENT_ENV = PICA8_ENV
