#!/usr/bin/python
# -*- coding: UTF-8 -*-

# basic settings
MIN_EXP_NUM = 0     # experiments number, just ignore this
MAX_EXP_NUM = 10 # please use shell to run multiple exp simultaneously
VNF_NUM = 16    # VNF type number
SFC_REQUEST_NUM = 100   # ignore this
SERVER_NUM = 20     # server number per ToR switch
SERVER_CLASSIFIER_NUM = 1   # Default is 1, used as the entrance of each SFC
NPOP_NUM = 6    

MIN_SFC_LENGTH = 2
MAX_SFC_LENGTH = 7

# # algorithm name
# ALGO_NAME_NOTVIA_PSFC = "NotVia + PSFC"
# ALGO_NAME_E2EP = "E2E-P"
# ALGO_NAME_UFRR = "MML-PSFC + MML-BSFC"
# ALGO_NAME_UFRR_ORTC = "ALGO_NAME_UFRR_ORTC"

# # metric
# METRIC_MAXIMUM_MAXE2ELATENCY = "METRIC_MAXIMUM_MAXE2ELATENCY"
# METRIC_MAXIMUM_MAXE2ELATENCY_CDF = "METRIC_MAXIMUM_MAXE2ELATENCY_CDF"
# METRIC_MAXIMUM_MAXE2ELATENCY_CDF = "METRIC_MAXIMUM_MAXE2ELATENCY_CDF"
# METRIC_MAXIMUM_MAXE2ELATENCY_NOFAILURE_WORSTCASE_CDF = "METRIC_MAXIMUM_MAXE2ELATENCY_NOFAILURE_WORSTCASE_CDF"
# METRIC_MAXIMUM_MAXE2ELATENCY_ITER_NPOPNUM = "METRIC_MAXIMUM_MAXE2ELATENCY_ITER_NPOPNUM"
# METRIC_MEDIAN_MAXE2ELATENCY_ITER_NPOPNUM = "METRIC_MEDIAN_MAXE2ELATENCY_ITER_NPOPNUM"
# METRIC_MAXIMUM_MAXE2ELATENCY_ITER_TOPOLOGY = "METRIC_MAXIMUM_MAXE2ELATENCY_ITER_TOPOLOGY"
# METRIC_MEDIAN_MAXE2ELATENCY_ITER_TOPOLOGY = "METRIC_MEDIAN_MAXE2ELATENCY_ITER_TOPOLOGY"
# METRIC_MAXIMUM_MAXE2ELATENCY_ITER_SFCLENGTH = "METRIC_MAXIMUM_MAXE2ELATENCY_ITER_SFCLENGTH"
# METRIC_MEDIAN_MAXE2ELATENCY_ITER_SFCLENGTH = "METRIC_MEDIAN_MAXE2ELATENCY_ITER_SFCLENGTH"
# METRIC_MAXIMUM_MAXE2ELATENCY_ITER_REQUESTNUM = "METRIC_MAXIMUM_MAXE2ELATENCY_ITER_REQUESTNUM"
# METRIC_MEDIAN_MAXE2ELATENCY_ITER_REQUESTNUM = "METRIC_MEDIAN_MAXE2ELATENCY_ITER_REQUESTNUM"

# METRIC_FIB = "FIB"
# METRIC_FIB_COMPRESSION_TIME = "METRIC_FIB_COMPRESSION_TIME"
# METRIC_FIB_COMPRESSION_TIME_ITER_TOPOLOGY = "METRIC_FIB_COMPRESSION_TIME_ITER_TOPOLOGY"
# METRIC_FIB_COMPRESSION_TIME_ITER_SFCLENGTH = "METRIC_FIB_COMPRESSION_TIME_ITER_SFCLENGTH"
# METRIC_FIB_COMPRESSION_RATIO_ITER_TOPOLOGY = "METRIC_FIB_COMPRESSION_RATIO_ITER_TOPOLOGY"
# METRIC_FIB_COMPRESSION_TIME_ITER_REQUESTNUM = "METRIC_FIB_COMPRESSION_TIME_ITER_REQUESTNUM"
# METRIC_FIB_SWITCH_CDF = "METRIC_FIB_SWITCH_CDF"
# METRIC_FLOW_ENTRY_SWITCH_CDF = "METRIC_FLOW_ENTRY_SWITCH_CDF"
# METRIC_GROUP_ENTRY_SWITCH_CDF = "METRIC_GROUP_ENTRY_SWITCH_CDF"
# METRIC_ENCODING_FORMAT_SWITCH_CDF = "METRIC_ENCODING_FORMAT_SWITCH_CDF"
# METRIC_FIB_SWITCH_ITER_TOPOLOGY = "METRIC_FIB_SWITCH_ITER_TOPOLOGY"
# METRIC_FIB_SWITCH_ITER_NPOPNUM = "METRIC_FIB_SWITCH_ITER_NPOPNUM"
# METRIC_FIB_SWITCH_ITER_SFCLENGTH = "METRIC_FIB_SWITCH_ITER_SFCLENGTH"
# METRIC_FIB_SWITCH_ITER_REQUESTNUM = "METRIC_FIB_SWITCH_ITER_REQUESTNUM"

# METRIC_LINKUTIL = "METRIC_LINKUTIL"

# topology
DEFAULT_LINK_LENGTH = 0.001 # unit: km
DEFAULT_LINK_BANDWIDTH = 1  # unit: Gbps
