#!/usr/bin/python
# -*- coding: UTF-8 -*-

SFC_DOMAIN_PREFIX = "10.0.0.0"
SFC_DOMAIN_PREFIX_LENGTH = 8  # DO NOT MODIFY THIS VALUE,
# otherwise BESS will incurr error
SFCID_LENGTH = 12  # DO NOT MODIFY THIS VALUE, otherwise BESS will incurr error

APP_TYPE_NORTHSOUTH_WEBSITE = "APP_TYPE_NORTHSOUTH_WEBSITE"
APP_TYPE_LARGE_BANDWIDTH = "APP_TYPE_LARGE_BANDWIDTH"
APP_TYPE_HIGH_AVA = "APP_TYPE_HIGH_AVA"
APP_TYPE_LOW_LATENCY = "APP_TYPE_LOW_LATENCY"
APP_TYPE_LARGE_CONNECTION = "APP_TYPE_LARGE_CONNECTION"
APP_TYPE_BEST_EFFORT = "APP_TYPE_BEST_EFFORT"

MANUAL_SCALE = "MANUAL_SCALE"
AUTO_SCALE = "AUTO_SCALE"

WITHOUT_PROTECTION = "WITHOUT_PROTECTION"
WITH_PROTECTION = "WITH_PROTECTION"

MANUAL_RECOVERY = "MANUAL_RECOVERY"
AUTO_RECOVERY = "AUTO_RECOVERY"

STATE_IN_PROCESSING = "STATE_IN_PROCESSING"
STATE_INIT_FAILED = "STATE_INIT_FAILED"
STATE_ACTIVE = "STATE_ACTIVE"
STATE_INACTIVE = "STATE_INACTIVE"  # There maybe some resource used in DCN
STATE_DELETED = "STATE_DELETED"  # All resource of this sfc/sfci has been released
STATE_UNDELETED = "STATE_UNDELETED"
STATE_MANUAL = "STATE_MANUAL"
# Warning: Delete an sfc/sfci will not release SFCIID
# To get back SFCIID, please prune sfc/sfci from database
STATE_RECOVER_MODE = "STATE_RECOVER_MODE"  # when a failure happen, sfc/sfci will be in this state
STATE_SCALING_OUT_MODE = "STATE_SCALING_OUT_MODE"  # when the sfc is scaling out, sfc will be in this state
STATE_SCALING_IN_MODE = "STATE_SCALING_IN_MODE" 

# SFCIID allocation
DASHBOARD_SFCIID_ALLOCATED_RANGE = [0, 10000]
REGULATOR_SFCIID_ALLOCATED_RANGE = [10001, 20000]

SFC_DIRECTION_0 = 0
SFC_DIRECTION_1 = 1