# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/messageAgentAuxillary/protos/messageAgent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4base/messageAgentAuxillary/protos/messageAgent.proto\"\x1d\n\x06Pickle\x12\x13\n\x0bpicklebytes\x18\x01 \x01(\x0c\"\x17\n\x06Status\x12\r\n\x05\x62ooly\x18\x01 \x01(\x08\x32-\n\x0eMessageStorage\x12\x1b\n\x05Store\x12\x07.Pickle\x1a\x07.Status\"\x00\x62\x06proto3')



_PICKLE = DESCRIPTOR.message_types_by_name['Pickle']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
Pickle = _reflection.GeneratedProtocolMessageType('Pickle', (_message.Message,), {
  'DESCRIPTOR' : _PICKLE,
  '__module__' : 'base.messageAgentAuxillary.protos.messageAgent_pb2'
  # @@protoc_insertion_point(class_scope:Pickle)
  })
_sym_db.RegisterMessage(Pickle)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'base.messageAgentAuxillary.protos.messageAgent_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  })
_sym_db.RegisterMessage(Status)

_MESSAGESTORAGE = DESCRIPTOR.services_by_name['MessageStorage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PICKLE._serialized_start=56
  _PICKLE._serialized_end=85
  _STATUS._serialized_start=87
  _STATUS._serialized_end=110
  _MESSAGESTORAGE._serialized_start=112
  _MESSAGESTORAGE._serialized_end=157
# @@protoc_insertion_point(module_scope)
